---

# ====================================================================================================================================

- name: BOOTSTRAPPING
  hosts: localhost
  
  vars:
    - ansible_deployer: "{{ lookup('env','ANSIBLE_DEPLOYER') }}"
    - artifacts: "{{ lookup('env','ARTIFACTS') }}"

# ------------------------------------------------------------------------------------------------------------------------------------

  become: yes
  become_user: "{{ ansible_deployer }}"
  
# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------

    - name: Create Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ artifacts }}/home/{{ ansible_deployer }}/.ssh"
        - "{{ artifacts }}/home/{{ ansible_deployer }}/.local"

# ------------------------------------------------------------------------------------------------------------------------------------

    - name: Copy SSH Files
      copy:
        src: "{{ item }}"
        dest: "{{ artifacts }}/home/{{ ansible_deployer }}/.ssh/"
      with_fileglob:
        - "~/.ssh/id_rsa_*"
        - "~/.ssh/authorized_keys"

    - name: Copy Gbin
      copy:
        src: "~/.local/gbin"
        dest: "{{ artifacts }}/home/{{ ansible_deployer }}/.local/"

# ====================================================================================================================================


