---

# ====================================================================================================================================

- name: PRULLCONFIG
  hosts: localhost

  vars:
    - ansible_deployer: "{{ lookup('env','ANSIBLE_DEPLOYER') }}"
    - artifacts: "{{ lookup('env','ARTIFACTS') }}"

# ------------------------------------------------------------------------------------------------------------------------------------

  become: yes
  become_user: "{{ ansible_deployer }}"
  
# ====================================================================================================================================

  tasks:

# ------------------------------------------------------------------------------------------------------------------------------------

    - name: Syncronize User Profile (pull)
      synchronize:
        mode: pull
        src: "~/"
        dest: "{{ artifacts }}/home/{{ ansible_deployer }}/"
        owner: no
        group: no
        perms: no
        recursive: yes
        existing_only: yes

# ====================================================================================================================================
